DF<-read.csv("household_power_consumption.txt", sep=";")
DFs<-subset(DF, Date=="1/2/2007"| Date=="2/2/2007")
DFs$datetime <- with(DFs, as.POSIXct(paste(Date, Time), format="%d/%m/%Y %H:%M:%S"))
DFs$weekDate<-weekdays(as.Date(DFs$Date, format="%d/%m/%Y"), abbreviate=TRUE)#final result of day depends on local language settings (plot from a machine set in italian)
DFs$Sub_metering_1<-as.numeric(paste(DFs$Sub_metering_1))
DFs$Sub_metering_2<-as.numeric(paste(DFs$Sub_metering_2))
DFs$Sub_metering_3<-as.numeric(paste(DFs$Sub_metering_3))
png(file="plot3.png")
plot(Sub_metering_1 ~ datetime, data=DFs, type="l", col="black", ylab="Energy sub metering", xlab="Day")
lines(Sub_metering_2 ~ datetime, data=DFs, type="l", col="red")
lines(Sub_metering_3 ~ datetime, data=DFs, type="l", col="blue")
legend("topright", col=c("black", "red", "blue"), legend=c("Sub_Metering_1", "Sub_Metering_2", "Sub_Metering_3"), lty=1)
dev.off()
